//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesManager.MesServiceTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MesServiceTest.IMesService")]
    public interface IMesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/TestCommunication", ReplyAction="http://tempuri.org/IMesService/TestCommunicationResponse")]
        string TestCommunication(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/TestCommunication", ReplyAction="http://tempuri.org/IMesService/TestCommunicationResponse")]
        System.Threading.Tasks.Task<string> TestCommunicationAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateTestResultData", ReplyAction="http://tempuri.org/IMesService/UpdateTestResultDataResponse")]
        string UpdateTestResultData(string sn, string typeNo, string station, string result, string teamLeader, string admin, string joinDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateTestResultData", ReplyAction="http://tempuri.org/IMesService/UpdateTestResultDataResponse")]
        System.Threading.Tasks.Task<string> UpdateTestResultDataAsync(string sn, string typeNo, string station, string result, string teamLeader, string admin, string joinDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectLastTestResult", ReplyAction="http://tempuri.org/IMesService/SelectLastTestResultResponse")]
        string[] SelectLastTestResult(string sn, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectLastTestResult", ReplyAction="http://tempuri.org/IMesService/SelectLastTestResultResponse")]
        System.Threading.Tasks.Task<string[]> SelectLastTestResultAsync(string sn, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateMaterialStatistics", ReplyAction="http://tempuri.org/IMesService/UpdateMaterialStatisticsResponse")]
        string UpdateMaterialStatistics(string typeNo, string stationName, string materialCode, string amounted, string teamLeader, string admin, string sn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateMaterialStatistics", ReplyAction="http://tempuri.org/IMesService/UpdateMaterialStatisticsResponse")]
        System.Threading.Tasks.Task<string> UpdateMaterialStatisticsAsync(string typeNo, string stationName, string materialCode, string amounted, string teamLeader, string admin, string sn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/CheckMaterialPutStorage", ReplyAction="http://tempuri.org/IMesService/CheckMaterialPutStorageResponse")]
        string CheckMaterialPutStorage(string materialCode, string teamLeader, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/CheckMaterialPutStorage", ReplyAction="http://tempuri.org/IMesService/CheckMaterialPutStorageResponse")]
        System.Threading.Tasks.Task<string> CheckMaterialPutStorageAsync(string materialCode, string teamLeader, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectMaterialSurplusAmount", ReplyAction="http://tempuri.org/IMesService/SelectMaterialSurplusAmountResponse")]
        string SelectMaterialSurplusAmount(string materialCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectMaterialSurplusAmount", ReplyAction="http://tempuri.org/IMesService/SelectMaterialSurplusAmountResponse")]
        System.Threading.Tasks.Task<string> SelectMaterialSurplusAmountAsync(string materialCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/CheckMaterialUseState", ReplyAction="http://tempuri.org/IMesService/CheckMaterialUseStateResponse")]
        string CheckMaterialUseState(string productTypeNo, string materialCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/CheckMaterialUseState", ReplyAction="http://tempuri.org/IMesService/CheckMaterialUseStateResponse")]
        System.Threading.Tasks.Task<string> CheckMaterialUseStateAsync(string productTypeNo, string materialCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/CheckMaterialMatch", ReplyAction="http://tempuri.org/IMesService/CheckMaterialMatchResponse")]
        string CheckMaterialMatch(string productTypeNo, string testMaterialPn, string actualMaterialPn, string materialCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/CheckMaterialMatch", ReplyAction="http://tempuri.org/IMesService/CheckMaterialMatchResponse")]
        System.Threading.Tasks.Task<string> CheckMaterialMatchAsync(string productTypeNo, string testMaterialPn, string actualMaterialPn, string materialCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdatePackageProductBindingMsg", ReplyAction="http://tempuri.org/IMesService/UpdatePackageProductBindingMsgResponse")]
        string[] UpdatePackageProductBindingMsg(string outCaseCode, string snOutter, string typeNo, string stationName, string bindingState, string remark, string teamLeader, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdatePackageProductBindingMsg", ReplyAction="http://tempuri.org/IMesService/UpdatePackageProductBindingMsgResponse")]
        System.Threading.Tasks.Task<string[]> UpdatePackageProductBindingMsgAsync(string outCaseCode, string snOutter, string typeNo, string stationName, string bindingState, string remark, string teamLeader, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateProgrameVersion", ReplyAction="http://tempuri.org/IMesService/UpdateProgrameVersionResponse")]
        string UpdateProgrameVersion(string typeNo, string stationName, string programePath, string programeName, string teamLeader, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateProgrameVersion", ReplyAction="http://tempuri.org/IMesService/UpdateProgrameVersionResponse")]
        System.Threading.Tasks.Task<string> UpdateProgrameVersionAsync(string typeNo, string stationName, string programePath, string programeName, string teamLeader, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateLimitConfig", ReplyAction="http://tempuri.org/IMesService/UpdateLimitConfigResponse")]
        string UpdateLimitConfig(string stationName, string typeNo, string testItem, string limit, string teamLeader, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateLimitConfig", ReplyAction="http://tempuri.org/IMesService/UpdateLimitConfigResponse")]
        System.Threading.Tasks.Task<string> UpdateLimitConfigAsync(string stationName, string typeNo, string testItem, string limit, string teamLeader, string admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateTestLog", ReplyAction="http://tempuri.org/IMesService/UpdateTestLogResponse")]
        string UpdateTestLog(string typeNo, string stationName, string productSN, string testItem, string limit, string currentValue, string testResult, string teamLeader, string admin, string joinDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdateTestLog", ReplyAction="http://tempuri.org/IMesService/UpdateTestLogResponse")]
        System.Threading.Tasks.Task<string> UpdateTestLogAsync(string typeNo, string stationName, string productSN, string testItem, string limit, string currentValue, string testResult, string teamLeader, string admin, string joinDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectCurrentTProcess", ReplyAction="http://tempuri.org/IMesService/SelectCurrentTProcessResponse")]
        string SelectCurrentTProcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectCurrentTProcess", ReplyAction="http://tempuri.org/IMesService/SelectCurrentTProcessResponse")]
        System.Threading.Tasks.Task<string> SelectCurrentTProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectAllTProcess", ReplyAction="http://tempuri.org/IMesService/SelectAllTProcessResponse")]
        string[] SelectAllTProcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectAllTProcess", ReplyAction="http://tempuri.org/IMesService/SelectAllTProcessResponse")]
        System.Threading.Tasks.Task<string[]> SelectAllTProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectStationList", ReplyAction="http://tempuri.org/IMesService/SelectStationListResponse")]
        string[] SelectStationList(string processName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectStationList", ReplyAction="http://tempuri.org/IMesService/SelectStationListResponse")]
        System.Threading.Tasks.Task<string[]> SelectStationListAsync(string processName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectTypeNoList", ReplyAction="http://tempuri.org/IMesService/SelectTypeNoListResponse")]
        string[] SelectTypeNoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectTypeNoList", ReplyAction="http://tempuri.org/IMesService/SelectTypeNoListResponse")]
        System.Threading.Tasks.Task<string[]> SelectTypeNoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectMaterialList", ReplyAction="http://tempuri.org/IMesService/SelectMaterialListResponse")]
        string[] SelectMaterialList(string productTypeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectMaterialList", ReplyAction="http://tempuri.org/IMesService/SelectMaterialListResponse")]
        System.Threading.Tasks.Task<string[]> SelectMaterialListAsync(string productTypeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/BindingPCBA", ReplyAction="http://tempuri.org/IMesService/BindingPCBAResponse")]
        string BindingPCBA(string snPCBA, string snOutter, string materialCode, string productTypeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/BindingPCBA", ReplyAction="http://tempuri.org/IMesService/BindingPCBAResponse")]
        System.Threading.Tasks.Task<string> BindingPCBAAsync(string snPCBA, string snOutter, string materialCode, string productTypeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectLimitConfig", ReplyAction="http://tempuri.org/IMesService/SelectLimitConfigResponse")]
        string[] SelectLimitConfig(string productTypeNo, string stationName, string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectLimitConfig", ReplyAction="http://tempuri.org/IMesService/SelectLimitConfigResponse")]
        System.Threading.Tasks.Task<string[]> SelectLimitConfigAsync(string productTypeNo, string stationName, string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectProgrameVersion", ReplyAction="http://tempuri.org/IMesService/SelectProgrameVersionResponse")]
        string[] SelectProgrameVersion(string productTypeNo, string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectProgrameVersion", ReplyAction="http://tempuri.org/IMesService/SelectProgrameVersionResponse")]
        System.Threading.Tasks.Task<string[]> SelectProgrameVersionAsync(string productTypeNo, string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectPackageStorage", ReplyAction="http://tempuri.org/IMesService/SelectPackageStorageResponse")]
        int SelectPackageStorage(string productTypeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/SelectPackageStorage", ReplyAction="http://tempuri.org/IMesService/SelectPackageStorageResponse")]
        System.Threading.Tasks.Task<int> SelectPackageStorageAsync(string productTypeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdatePackageStorage", ReplyAction="http://tempuri.org/IMesService/UpdatePackageStorageResponse")]
        string UpdatePackageStorage(string productTypeNo, int capacity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdatePackageStorage", ReplyAction="http://tempuri.org/IMesService/UpdatePackageStorageResponse")]
        System.Threading.Tasks.Task<string> UpdatePackageStorageAsync(string productTypeNo, int capacity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/QueryPCBAMes", ReplyAction="http://tempuri.org/IMesService/QueryPCBAMesResponse")]
        System.Data.DataSet QueryPCBAMes(string pcbasn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/QueryPCBAMes", ReplyAction="http://tempuri.org/IMesService/QueryPCBAMesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> QueryPCBAMesAsync(string pcbasn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdatePcbaBindingState", ReplyAction="http://tempuri.org/IMesService/UpdatePcbaBindingStateResponse")]
        bool UpdatePcbaBindingState(string pcbaSn, string outterSn, int bindingState, int pcbaState, int outterState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdatePcbaBindingState", ReplyAction="http://tempuri.org/IMesService/UpdatePcbaBindingStateResponse")]
        System.Threading.Tasks.Task<bool> UpdatePcbaBindingStateAsync(string pcbaSn, string outterSn, int bindingState, int pcbaState, int outterState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdatePCBABindingRepaireState", ReplyAction="http://tempuri.org/IMesService/UpdatePCBABindingRepaireStateResponse")]
        bool UpdatePCBABindingRepaireState(string pcbaSn, string outterSn, int bindingState, int pcbaState, int outterState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/UpdatePCBABindingRepaireState", ReplyAction="http://tempuri.org/IMesService/UpdatePCBABindingRepaireStateResponse")]
        System.Threading.Tasks.Task<bool> UpdatePCBABindingRepaireStateAsync(string pcbaSn, string outterSn, int bindingState, int pcbaState, int outterState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/CheckPcbaState", ReplyAction="http://tempuri.org/IMesService/CheckPcbaStateResponse")]
        string[] CheckPcbaState(string snPcba, string snOutter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/CheckPcbaState", ReplyAction="http://tempuri.org/IMesService/CheckPcbaStateResponse")]
        System.Threading.Tasks.Task<string[]> CheckPcbaStateAsync(string snPcba, string snOutter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/Login", ReplyAction="http://tempuri.org/IMesService/LoginResponse")]
        string[] Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/Login", ReplyAction="http://tempuri.org/IMesService/LoginResponse")]
        System.Threading.Tasks.Task<string[]> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/GetUserInfo", ReplyAction="http://tempuri.org/IMesService/GetUserInfoResponse")]
        string[] GetUserInfo(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/GetUserInfo", ReplyAction="http://tempuri.org/IMesService/GetUserInfoResponse")]
        System.Threading.Tasks.Task<string[]> GetUserInfoAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/Register", ReplyAction="http://tempuri.org/IMesService/RegisterResponse")]
        string[] Register(string username, string pwd, int userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/Register", ReplyAction="http://tempuri.org/IMesService/RegisterResponse")]
        System.Threading.Tasks.Task<string[]> RegisterAsync(string username, string pwd, int userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/ModifyUserPassword", ReplyAction="http://tempuri.org/IMesService/ModifyUserPasswordResponse")]
        string[] ModifyUserPassword(string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/ModifyUserPassword", ReplyAction="http://tempuri.org/IMesService/ModifyUserPasswordResponse")]
        System.Threading.Tasks.Task<string[]> ModifyUserPasswordAsync(string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/DeleteUser", ReplyAction="http://tempuri.org/IMesService/DeleteUserResponse")]
        string[] DeleteUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesService/DeleteUser", ReplyAction="http://tempuri.org/IMesService/DeleteUserResponse")]
        System.Threading.Tasks.Task<string[]> DeleteUserAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesServiceChannel : MesManager.MesServiceTest.IMesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesServiceClient : System.ServiceModel.ClientBase<MesManager.MesServiceTest.IMesService>, MesManager.MesServiceTest.IMesService {
        
        public MesServiceClient() {
        }
        
        public MesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestCommunication(string value) {
            return base.Channel.TestCommunication(value);
        }
        
        public System.Threading.Tasks.Task<string> TestCommunicationAsync(string value) {
            return base.Channel.TestCommunicationAsync(value);
        }
        
        public string UpdateTestResultData(string sn, string typeNo, string station, string result, string teamLeader, string admin, string joinDateTime) {
            return base.Channel.UpdateTestResultData(sn, typeNo, station, result, teamLeader, admin, joinDateTime);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTestResultDataAsync(string sn, string typeNo, string station, string result, string teamLeader, string admin, string joinDateTime) {
            return base.Channel.UpdateTestResultDataAsync(sn, typeNo, station, result, teamLeader, admin, joinDateTime);
        }
        
        public string[] SelectLastTestResult(string sn, string station) {
            return base.Channel.SelectLastTestResult(sn, station);
        }
        
        public System.Threading.Tasks.Task<string[]> SelectLastTestResultAsync(string sn, string station) {
            return base.Channel.SelectLastTestResultAsync(sn, station);
        }
        
        public string UpdateMaterialStatistics(string typeNo, string stationName, string materialCode, string amounted, string teamLeader, string admin, string sn) {
            return base.Channel.UpdateMaterialStatistics(typeNo, stationName, materialCode, amounted, teamLeader, admin, sn);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMaterialStatisticsAsync(string typeNo, string stationName, string materialCode, string amounted, string teamLeader, string admin, string sn) {
            return base.Channel.UpdateMaterialStatisticsAsync(typeNo, stationName, materialCode, amounted, teamLeader, admin, sn);
        }
        
        public string CheckMaterialPutStorage(string materialCode, string teamLeader, string admin) {
            return base.Channel.CheckMaterialPutStorage(materialCode, teamLeader, admin);
        }
        
        public System.Threading.Tasks.Task<string> CheckMaterialPutStorageAsync(string materialCode, string teamLeader, string admin) {
            return base.Channel.CheckMaterialPutStorageAsync(materialCode, teamLeader, admin);
        }
        
        public string SelectMaterialSurplusAmount(string materialCode) {
            return base.Channel.SelectMaterialSurplusAmount(materialCode);
        }
        
        public System.Threading.Tasks.Task<string> SelectMaterialSurplusAmountAsync(string materialCode) {
            return base.Channel.SelectMaterialSurplusAmountAsync(materialCode);
        }
        
        public string CheckMaterialUseState(string productTypeNo, string materialCode) {
            return base.Channel.CheckMaterialUseState(productTypeNo, materialCode);
        }
        
        public System.Threading.Tasks.Task<string> CheckMaterialUseStateAsync(string productTypeNo, string materialCode) {
            return base.Channel.CheckMaterialUseStateAsync(productTypeNo, materialCode);
        }
        
        public string CheckMaterialMatch(string productTypeNo, string testMaterialPn, string actualMaterialPn, string materialCode) {
            return base.Channel.CheckMaterialMatch(productTypeNo, testMaterialPn, actualMaterialPn, materialCode);
        }
        
        public System.Threading.Tasks.Task<string> CheckMaterialMatchAsync(string productTypeNo, string testMaterialPn, string actualMaterialPn, string materialCode) {
            return base.Channel.CheckMaterialMatchAsync(productTypeNo, testMaterialPn, actualMaterialPn, materialCode);
        }
        
        public string[] UpdatePackageProductBindingMsg(string outCaseCode, string snOutter, string typeNo, string stationName, string bindingState, string remark, string teamLeader, string admin) {
            return base.Channel.UpdatePackageProductBindingMsg(outCaseCode, snOutter, typeNo, stationName, bindingState, remark, teamLeader, admin);
        }
        
        public System.Threading.Tasks.Task<string[]> UpdatePackageProductBindingMsgAsync(string outCaseCode, string snOutter, string typeNo, string stationName, string bindingState, string remark, string teamLeader, string admin) {
            return base.Channel.UpdatePackageProductBindingMsgAsync(outCaseCode, snOutter, typeNo, stationName, bindingState, remark, teamLeader, admin);
        }
        
        public string UpdateProgrameVersion(string typeNo, string stationName, string programePath, string programeName, string teamLeader, string admin) {
            return base.Channel.UpdateProgrameVersion(typeNo, stationName, programePath, programeName, teamLeader, admin);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProgrameVersionAsync(string typeNo, string stationName, string programePath, string programeName, string teamLeader, string admin) {
            return base.Channel.UpdateProgrameVersionAsync(typeNo, stationName, programePath, programeName, teamLeader, admin);
        }
        
        public string UpdateLimitConfig(string stationName, string typeNo, string testItem, string limit, string teamLeader, string admin) {
            return base.Channel.UpdateLimitConfig(stationName, typeNo, testItem, limit, teamLeader, admin);
        }
        
        public System.Threading.Tasks.Task<string> UpdateLimitConfigAsync(string stationName, string typeNo, string testItem, string limit, string teamLeader, string admin) {
            return base.Channel.UpdateLimitConfigAsync(stationName, typeNo, testItem, limit, teamLeader, admin);
        }
        
        public string UpdateTestLog(string typeNo, string stationName, string productSN, string testItem, string limit, string currentValue, string testResult, string teamLeader, string admin, string joinDateTime) {
            return base.Channel.UpdateTestLog(typeNo, stationName, productSN, testItem, limit, currentValue, testResult, teamLeader, admin, joinDateTime);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTestLogAsync(string typeNo, string stationName, string productSN, string testItem, string limit, string currentValue, string testResult, string teamLeader, string admin, string joinDateTime) {
            return base.Channel.UpdateTestLogAsync(typeNo, stationName, productSN, testItem, limit, currentValue, testResult, teamLeader, admin, joinDateTime);
        }
        
        public string SelectCurrentTProcess() {
            return base.Channel.SelectCurrentTProcess();
        }
        
        public System.Threading.Tasks.Task<string> SelectCurrentTProcessAsync() {
            return base.Channel.SelectCurrentTProcessAsync();
        }
        
        public string[] SelectAllTProcess() {
            return base.Channel.SelectAllTProcess();
        }
        
        public System.Threading.Tasks.Task<string[]> SelectAllTProcessAsync() {
            return base.Channel.SelectAllTProcessAsync();
        }
        
        public string[] SelectStationList(string processName) {
            return base.Channel.SelectStationList(processName);
        }
        
        public System.Threading.Tasks.Task<string[]> SelectStationListAsync(string processName) {
            return base.Channel.SelectStationListAsync(processName);
        }
        
        public string[] SelectTypeNoList() {
            return base.Channel.SelectTypeNoList();
        }
        
        public System.Threading.Tasks.Task<string[]> SelectTypeNoListAsync() {
            return base.Channel.SelectTypeNoListAsync();
        }
        
        public string[] SelectMaterialList(string productTypeNo) {
            return base.Channel.SelectMaterialList(productTypeNo);
        }
        
        public System.Threading.Tasks.Task<string[]> SelectMaterialListAsync(string productTypeNo) {
            return base.Channel.SelectMaterialListAsync(productTypeNo);
        }
        
        public string BindingPCBA(string snPCBA, string snOutter, string materialCode, string productTypeNo) {
            return base.Channel.BindingPCBA(snPCBA, snOutter, materialCode, productTypeNo);
        }
        
        public System.Threading.Tasks.Task<string> BindingPCBAAsync(string snPCBA, string snOutter, string materialCode, string productTypeNo) {
            return base.Channel.BindingPCBAAsync(snPCBA, snOutter, materialCode, productTypeNo);
        }
        
        public string[] SelectLimitConfig(string productTypeNo, string stationName, string item) {
            return base.Channel.SelectLimitConfig(productTypeNo, stationName, item);
        }
        
        public System.Threading.Tasks.Task<string[]> SelectLimitConfigAsync(string productTypeNo, string stationName, string item) {
            return base.Channel.SelectLimitConfigAsync(productTypeNo, stationName, item);
        }
        
        public string[] SelectProgrameVersion(string productTypeNo, string stationName) {
            return base.Channel.SelectProgrameVersion(productTypeNo, stationName);
        }
        
        public System.Threading.Tasks.Task<string[]> SelectProgrameVersionAsync(string productTypeNo, string stationName) {
            return base.Channel.SelectProgrameVersionAsync(productTypeNo, stationName);
        }
        
        public int SelectPackageStorage(string productTypeNo) {
            return base.Channel.SelectPackageStorage(productTypeNo);
        }
        
        public System.Threading.Tasks.Task<int> SelectPackageStorageAsync(string productTypeNo) {
            return base.Channel.SelectPackageStorageAsync(productTypeNo);
        }
        
        public string UpdatePackageStorage(string productTypeNo, int capacity) {
            return base.Channel.UpdatePackageStorage(productTypeNo, capacity);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePackageStorageAsync(string productTypeNo, int capacity) {
            return base.Channel.UpdatePackageStorageAsync(productTypeNo, capacity);
        }
        
        public System.Data.DataSet QueryPCBAMes(string pcbasn) {
            return base.Channel.QueryPCBAMes(pcbasn);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> QueryPCBAMesAsync(string pcbasn) {
            return base.Channel.QueryPCBAMesAsync(pcbasn);
        }
        
        public bool UpdatePcbaBindingState(string pcbaSn, string outterSn, int bindingState, int pcbaState, int outterState) {
            return base.Channel.UpdatePcbaBindingState(pcbaSn, outterSn, bindingState, pcbaState, outterState);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePcbaBindingStateAsync(string pcbaSn, string outterSn, int bindingState, int pcbaState, int outterState) {
            return base.Channel.UpdatePcbaBindingStateAsync(pcbaSn, outterSn, bindingState, pcbaState, outterState);
        }
        
        public bool UpdatePCBABindingRepaireState(string pcbaSn, string outterSn, int bindingState, int pcbaState, int outterState) {
            return base.Channel.UpdatePCBABindingRepaireState(pcbaSn, outterSn, bindingState, pcbaState, outterState);
        }
        
        public System.Threading.Tasks.Task<bool> UpdatePCBABindingRepaireStateAsync(string pcbaSn, string outterSn, int bindingState, int pcbaState, int outterState) {
            return base.Channel.UpdatePCBABindingRepaireStateAsync(pcbaSn, outterSn, bindingState, pcbaState, outterState);
        }
        
        public string[] CheckPcbaState(string snPcba, string snOutter) {
            return base.Channel.CheckPcbaState(snPcba, snOutter);
        }
        
        public System.Threading.Tasks.Task<string[]> CheckPcbaStateAsync(string snPcba, string snOutter) {
            return base.Channel.CheckPcbaStateAsync(snPcba, snOutter);
        }
        
        public string[] Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string[]> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string[] GetUserInfo(string username) {
            return base.Channel.GetUserInfo(username);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUserInfoAsync(string username) {
            return base.Channel.GetUserInfoAsync(username);
        }
        
        public string[] Register(string username, string pwd, int userType) {
            return base.Channel.Register(username, pwd, userType);
        }
        
        public System.Threading.Tasks.Task<string[]> RegisterAsync(string username, string pwd, int userType) {
            return base.Channel.RegisterAsync(username, pwd, userType);
        }
        
        public string[] ModifyUserPassword(string username, string pwd) {
            return base.Channel.ModifyUserPassword(username, pwd);
        }
        
        public System.Threading.Tasks.Task<string[]> ModifyUserPasswordAsync(string username, string pwd) {
            return base.Channel.ModifyUserPasswordAsync(username, pwd);
        }
        
        public string[] DeleteUser(string username) {
            return base.Channel.DeleteUser(username);
        }
        
        public System.Threading.Tasks.Task<string[]> DeleteUserAsync(string username) {
            return base.Channel.DeleteUserAsync(username);
        }
    }
}
